# -*- coding: utf-8 -*-
"""Projet_iovision.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10O1BXViawM_LOme_Ql8ODFuoB4FKL731
"""

import requests
from bs4 import BeautifulSoup
category=[]
baseurl = "https://shop.mango.com/"
k = requests.get(baseurl+'qa-en/women').text
soup=BeautifulSoup(k,'html.parser')
categoryhtml=[]
for i in range(1,3):
    categoryhtml.extend(soup.find_all("div",{"class":"vsv-banner vsv-column"+str(i)}))
len(categoryhtml)

for i in categoryhtml:
    category.append({'categName':i.find("h2",{"class":"vsv-title"}).text , 'link': baseurl +i.find("a",{"class":"vsv-link"}).get('href')})
category

